-- Active: 1758424882115@@127.0.0.1@5432@datalake@staging
-- Generated by the database client.
-- CREATE TABLE staging.cargos(
--     id SERIAL NOT NULL,
--     nome varchar(100) NOT NULL,
--     descricao text,
--     max_nivel integer NOT NULL DEFAULT 5,
--     PRIMARY KEY(id),
--     CONSTRAINT cargos_max_nivel_check CHECK ((max_nivel >= 1) AND (max_nivel <= 5))
-- ) ;
-- CREATE UNIQUE INDEX cargos_nome_key ON staging.cargos USING btree (nome);



-- -- Generated by the database client.
-- CREATE TABLE staging.departamento_cargos(
--     id SERIAL NOT NULL,
--     departamento_id integer NOT NULL,
--     cargo_id integer NOT NULL,
--     PRIMARY KEY(id),
--     CONSTRAINT departamento_cargos_departamento_id_fkey FOREIGN key(departamento_id) REFERENCES departamentos(id),
--     CONSTRAINT departamento_cargos_cargo_id_fkey FOREIGN key(cargo_id) REFERENCES cargos(id)
-- ) ;
-- CREATE UNIQUE INDEX departamento_cargos_departamento_id_cargo_id_key ON staging.departamento_cargos USING btree (departamento_id, cargo_id);

-- Generated by the database client.
-- CREATE TABLE staging.departamentos(
--     id SERIAL NOT NULL,
--     nome varchar(150) NOT NULL,
--     descricao text,
--     PRIMARY KEY(id)
-- ) ;
-- CREATE UNIQUE INDEX departamentos_nome_key ON staging.departamentos USING btree (nome);


-- Generated by the database client.
-- CREATE TABLE staging.niveis_permissao(
--     id SERIAL NOT NULL,
--     nivel integer NOT NULL,
--     descricao text,
--     PRIMARY KEY(id),
--     CONSTRAINT niveis_permissao_nivel_check CHECK ((nivel >= 1) AND (nivel <= 10))
-- ) ;
-- CREATE UNIQUE INDEX niveis_permissao_nivel_key ON staging.niveis_permissao USING btree (nivel);

-- Generated by the database client.
CREATE TABLE staging.salarios(
    id SERIAL NOT NULL,
    cargo_id integer NOT NULL,
    nivel_cargo integer NOT NULL,
    salario numeric(12,2) NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT salarios_cargo_id_fkey FOREIGN key(cargo_id) REFERENCES staging.cargos(id),
    CONSTRAINT salarios_nivel_cargo_check CHECK ((nivel_cargo >= 1) AND (nivel_cargo <= 5)),
    CONSTRAINT salarios_salario_check CHECK (salario >= (0)::numeric)
) ;
CREATE UNIQUE INDEX salarios_cargo_id_nivel_cargo_key ON staging.salarios USING btree (cargo_id, nivel_cargo);

-- Generated by the database client.
CREATE TABLE staging.sistemas(
    id SERIAL NOT NULL,
    nome varchar(150) NOT NULL,
    descricao text,
    PRIMARY KEY(id)
) ;
CREATE UNIQUE INDEX sistemas_nome_key ON staging.sistemas USING btree (nome);

-- Generated by the database client.
CREATE TABLE staging.usuarios(
    id SERIAL NOT NULL,
    nome varchar(100) NOT NULL,
    sobrenome varchar(100) NOT NULL,
    cpf character(11) NOT NULL,
    nivel_permissao_id integer NOT NULL,
    cargo_id integer NOT NULL,
    gerente_id integer,
    data_nascimento date NOT NULL,
    data_admissao date NOT NULL,
    status boolean NOT NULL DEFAULT true,
    departamento_id integer,
    PRIMARY KEY(id),
    CONSTRAINT usuarios_nivel_permissao_id_fkey FOREIGN key(nivel_permissao_id) REFERENCES staging.niveis_permissao(id),
    CONSTRAINT usuarios_cargo_id_fkey FOREIGN key(cargo_id) REFERENCES staging.cargos(id),
    CONSTRAINT usuarios_gerente_id_fkey FOREIGN key(gerente_id) REFERENCES staging.usuarios(id),
    CONSTRAINT usuarios_departamento_id_fkey FOREIGN key(departamento_id) REFERENCES staging.departamentos(id)
) ;
CREATE UNIQUE INDEX usuarios_cpf_key ON staging.usuarios USING btree (cpf);


-- Generated by the database client.
CREATE TABLE usuarios_sistemas(
    id SERIAL NOT NULL,
    usuario_id integer NOT NULL,
    sistema_id integer NOT NULL,
    nivel_permissao_id integer NOT NULL,
    liberado_por integer NOT NULL,
    data_liberacao timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ativo boolean NOT NULL DEFAULT true,
    PRIMARY KEY(id),
    CONSTRAINT usuarios_sistemas_usuario_id_fkey FOREIGN key(usuario_id) REFERENCES staging.usuarios(id),
    CONSTRAINT usuarios_sistemas_sistema_id_fkey FOREIGN key(sistema_id) REFERENCES staging.sistemas(id),
    CONSTRAINT usuarios_sistemas_nivel_permissao_id_fkey FOREIGN key(nivel_permissao_id) REFERENCES staging.niveis_permissao(id),
    CONSTRAINT usuarios_sistemas_liberado_por_fkey FOREIGN key(liberado_por) REFERENCES staging.usuarios(id)
) ;
CREATE UNIQUE INDEX usuarios_sistemas_usuario_id_sistema_id_key ON staging.usuarios_sistemas USING btree (usuario_id, sistema_id);